language: cpp

matrix:
  include:
    - name: Linux GCC 7
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: Linux Clang 5
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - name: Linux Clang 8
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - name: Mac Clang (Xcode 9)
      os: osx
      osx_image: xcode9
      
before_install:
    - eval "${MATRIX_EVAL}"

script: "cd build_cmake && ./build.sh"
